project:
  type: website
  output-dir: docs

website:
  title: "Maternal Mortality During the COVID-19 Pandemic"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: quartz
    css: styles.css



