---
title: "Blog Post 2: Comorbidities"
editor: visual
---

Morbidities can pave the way for mortality. As morbidities increase, so do mortality and the risks that are associated with pregnancy. These include “chronic hypertension, gestational hypertension or preeclampsia, pregestational diabetes mellitus, and previous preterm birth, and lower rates of tobacco use” (Gulersen et al., 2022, p. 1). Chronic diseases like these are quickly becoming more prevalent in the United States (Bodenheimer et al., 2009). This is scary because, with the addition of multiple comorbidities, there is an increased risk of mortality. Throughout the COVID-19 pandemic, mortality associated with pregnancy and childbirth increased and it was shown that the rates of in-hospital deaths had increased (Simeone et al., 2021). However, it is hard to say if they were caused by COVID-19 or by the confounding effects that the coronavirus has on pre-existing conditions in pregnant women. Unfortunately, many of these comorbidities come with their friends. As a person ages, they become more susceptible to the snowball effect of these chronic diseases. Smith also found that “pregnant women with 3 underlying health conditions had over twice the risk of moderate-to-severe COVID-19 illness compared with those with no comorbidities” (Smith et al., 2023, pg. 163). Although little research has been done to establish cause, it is reasonable to think that comorbidities could be playing a key role in the deaths of pregnant women during the pandemic. 

In a study done by Simeone and colleagues, it was revealed that deliveries in 2020 had a higher chance of death. There were 53 in-hospital deaths, while in 2019, there were 33, an increase of 69%. When the researchers in this study removed the women who had COVID-19 during labor, this number was no longer significant, meaning that COVID-19 had a significant role in the increase in deaths from 2019 to 2020 (Simeone et al., 2021). But why is this happening? COVID-19 can be considered a comorbidity and increases the severity of preexisting conditions. The women who died also had preexisting comorbidities that exacerbated the symptoms of COVID-19, to the point where they became deadly. The coronavirus takes over its host’s respiratory system. Because every bodily function requires the use of oxygen and energy, it becomes extremely hard for bodies that are already dealing with preexisting conditions to fight off COVID. Then when you add another body, sharing resources with its mother, a pregnant woman is fighting to get enough nutrients and oxygen to supply both her and the fetus. Women with a COVID-19 diagnosis had higher rates of pregnancy-induced hypertension and preeclampsia/eclampsia. Because of this, pregnant people were highly recommended to strictly abide by all COVID-19 prevention measures throughout the pandemic (Villar et al., 2021) to reduce the risk of maternal mortality. Those who were already dealing with diabetes, hypertension, being overweight, cardiac diseases, and chronic respiratory diseases were at a higher risk for complications from COVID-19. A study done by Smith and colleagues revealed that for those with a positive coronavirus test, the “risk of mortality was 3.79 times higher for pregnant women with preexisting diabetes mellitus, 2.75 times higher for those with preexisting hypertension, and 16.75 times higher for those with cardiovascular disease compared to those without these chronic health conditions” (Smith et al., 2023, pg. 166). As the prevalence of these diseases is increasing, and there are new mutations of COVID-19 emerging, the risk of maternal mortality could continue to rise. These comorbidities are also heavily influenced by social determinants of health, with the prevalence increasing as factors like socioeconomic status, food security, race, and more are involved. In the next blog post, we explore the key interactions between comorbidities, SDOHs, and state COVID-19 policies.
