---
title: "Blog Post 3: Social Determinants of Health"
editor: visual
---

Social determinants of health (SDOHs) are the unchangeable aspects of a person’s life that directly affect their well-being (Braveman, 2023). These include race, ethnicity, socioeconomic status, educational attainment, age, and location. By having a different skin tone, or by being born in certain neighborhoods, people suffer the consequences of systematic disadvantage. SDOHs can have a direct impact on the health of an expecting person. For example, women of color are subjected to racism within medical communities and are often left feeling unheard by providers (Villarosa, 2018). Another example includes hospital funding: if a pregnant woman lives in an affluent area, the closest hospital to her is likely to be stocked with the best providers and resources available.

Before COVID-19, the US already had disappointing maternal health statistics. The country had the highest percentage of maternal mortality and morbidity for a developed nation (MacDorman et al., 2017). Trost and colleagues focused on pregnancy-related deaths from 2017-2019 and found race, ethnicity, age, education level, and location were major factors for maternal mortality. Those who are underserved and less privileged are at a higher risk of death, with many of these deaths being preventable (Trost et al., 2022). About 84.2% of the pregnancy-related deaths that occurred in the US between 2017 and 2019 were considered preventable (Trost et al., 2022). 

To further understand preventability, let’s talk about race. Due to systematic oppression and low levels of trust in the medical system, black women have a higher incidence of stress during pregnancy (Villarosa, 2018). This lack of trust stems from not feeling heard by providers and therefore not receiving an adequate level of care. Stress can raise blood pressure, disrupt hormones, and put the body into a state of fight or flight. All these stress responses factor into the development of comorbidities that can be deadly during pregnancy. These additional morbidities then cause adverse maternal and infant health outcomes like low birth weight and maternal conditions like pre-eclampsia, which can lead to deathly outcomes like uterine bleeding and seizures. 
Those with a lower socioeconomic status also have a higher incidence of poor birthing outcomes. This can be due to a lack of insurance, being unable to pay hospital bills, not being able to afford prenatal care, or the health problems associated with having a low SES (Blumenshine et al., 2010). One of these health problems is obesity. Obesity caused by low SES stems from food insecurity. Typically, nutritious foods are more expensive than highly processed and sugary options. This leaves many families’ only options being fast food or skipping meals altogether. When all a person can afford is food that does not provide any real nutrition, it is easy to become obese. Also, when people are struggling to make ends meet, it is incredibly hard to find the time to exercise. If an expecting woman is trying to work two jobs, she most likely does not have time to sneak in a walk or go to the gym. When considering these factors, we can consider obesity as an outcome of SDOHs. Obesity can lead to complications in pregnancy and birth because it increases the risk of developing preeclampsia and other blood pressure-related disorders. The conditions that cause obesity are what lead to maternal mortality in some cases. In 2019, one study identified that 12.7% of mothers were obese; this study further revealed that 33 women died (Simeone et al., 2021). Using these numbers, we can estimate that about 4 of these women were obese. 
COVID-19 disproportionately affected people of color and those with low socioeconomic status. This is mainly because the pandemic widened gaps that were already existing within our medical system. In a study done by Metz and colleagues, five women who died due to pregnancy-related complications had tested positive for COVID-19 at the time of death (Metz et al., 2022). Although there is evidence of increased risk, there is no evidence to suggest a concrete link between COVID and pregnancy-related death. It does, however, reveal the interaction between symptoms of COVID-19 and how women are treated within our healthcare system. People of color are at higher risk of contracting COVID-19. The higher prevalence in the minority community stems from barriers to accessing PPE supplies, misinformation, and distrust in the medical system (Tai et al., 2021). These reasons compounded with the SDOHs that outdate the pandemic, made these groups more susceptible to infection. People of color also have a higher risk of negative birth outcomes due to systematic racism. Though race did not have statistical significance in this study, vulnerable groups are already marginalized within the birthing world (Metz et al., 2022). The multiplicative effect of the increased prevalence of coronavirus in people of color and the proven negative birth outcomes on moms of color, show a scary correlation of the indifference in the US medical system. This is setting people up to die. This study was conducted before many of the COVID-19 variants began to spread but it would be valuable to see how pregnant women of color were affected by the more infectious and deadly variants of the virus. 

In March 2020, New York City saw a higher number of new mothers admitted to the ICU. These women were COVID-19-positive and obese. Because the coronavirus makes the respiratory and circulatory systems work overtime, those with increased blood pressure and reduced lung capabilities, suffer more severe symptoms. These women had to be intubated during delivery and experienced preterm births (Khoury et al., 2020). As discussed earlier, obesity is often a consequence of having low SES. Obesity was associated with COVID-19 severity which was in turn associated with the likelihood of receiving a C-section or preterm birth. Those with severe COVID-19 were more likely to deliver via Cesarean Section. There were no maternal deaths in this study but a lot of scary outcomes. C-Sections are major surgeries that come with many risks of their own, including “risks from anesthesia, blood loss, infection, a longer recovery period and potential for a higher risk of postpartum depression” (C-Section vs. Natural Birth, 2021). New mothers cannot lift more than fifteen pounds, find comfortable breastfeeding positions that do not interfere with their incision site,  and will have to seek pain management (Changes to Expect after a C-Section, n.d.). As COVID-19 continues to mutate, it is important to know how obese, pregnant women will react to the disease because mutations could become deadlier to those dealing with increased blood pressure. 

What is clear is how powerful the social determinants of health are in relation to pregnancy and health, specifically maternal and infant health. The next blog post will focus on the effects of comorbidities on pregnancy and COVID-19. 
