---
title: "Blog Post 1: Defining and Measuring Maternal Mortality Before and During COVID"
editor: visual
---

Before you jump in and begin the blog, here is a list of key terms that are crucial to understand:

•	**Maternal Mortality:** The World Health Organization defines maternal mortality as, “female deaths from any cause related to or aggravated by pregnancy or its management (excluding accidental or incidental causes) during pregnancy and childbirth or within 42 days of termination of pregnancy, irrespective of the duration and site of the pregnancy” (Indicator Metadata Registry Details, n.d.).

•	**Maternal Morbidity:** “any health condition attributed to and/or aggravated by pregnancy and childbirth that has negative outcomes to the woman’s well-being” (What Are Maternal Morbidity and Mortality? | Office of Research on Women’s Health, n.d.).

•	**Preventable Death:** means that “there was at least some chance of the death being adverted by one or more reasonable changes to patient, community, provider, facility, and/or systems factors” (Trost et al., 2022, pg. 5).

•	**Maternal Mortality Rates:** the number of pregnancy-related deaths divided by the total number of maternal deaths in each state.


A lot can be said about the overall health of a nation based on the health outcomes of its most vulnerable populations: women and children.  When a nation does not take proper precautions to guarantee protection from the fatality of its vulnerable populations, they are not providing citizens with adequate resources of life. The United States is a developed country that is struggling with maternal mortality. In the US, about 700 women die every year from pregnancy-related complications, which is more than in any other developed nation (What Are Maternal Morbidity and Mortality? | Office of Research on Women’s Health, n.d.). While this statistic is heartbreaking, it is even more shocking when we realize that about half of these deaths are deemed preventable. This became incredibly clear throughout the COVID-19 pandemic as the effects of social determinants of health and comorbidities were worsened by the symptoms of coronavirus.   

As of early 2024, little research has been done to see if the pandemic had a major effect on the rates of adverse maternal health outcomes in the United States. It is particularly important to know how major public health events shape the lives of our nation’s mothers and their children. This project will look at the research that has already been done and aim to decipher how, where, and why COVID-19 is affecting pregnant women in America. The blog posts will examine the pandemic's effect on maternal mortality. 

To understand the overarching idea of this blog, it is important to know how maternal mortality is measured in the United States. Since 2003, maternal mortality has been reported via the U.S. standard death certificate where a box is checked off to “ascertain whether the female decedents were not pregnant within the past year, pregnant at the time of death, not pregnant within 42 days of death, not pregnant but pregnant 43 days to 1 year before death, or unknown if pregnant within the past year” (MacDorman et al., 2017). These checkboxes are believed to be a flawed system because it is susceptible to human error. This can underestimate the number of maternal deaths in a year. Boxes that were supposed to be marked could be forgotten or the cause of death could be wrong, therefore leaving a maternal death unmarked. Because of the imperfect system, new policies are suggesting that “Hospitals and systems should improve death certificate quality through medical certifier training and support. Medical schools should consider making this education a requirement for completion of medical school. The CDC offers a guide for completion of medical certifications of death” (Brown & Canzoneri, 2021). Maternal death review committees serve to look at the cause of death and to use that information to prevent future deaths from happening. Because COVID-19 is a pressing public health issue, some states are pushing to review deaths during this period faster to see if there is a connection to the pandemic. Pre-existing conditions such as hypertension, obesity, and diabetes, already factors for more severe COVID-19, also have an impact on pregnant women that could have a multiplicative effect on the adverse outcomes. We need to understand if the death was caused by COVID-19 or a comorbidity that was exaggerated by the effects of the coronavirus (Metz et al., 2020).

Later in the blog, I will visually represent the maternal mortality rates throughout the country. This will be done by analyzing data compiled by MuckRock. MuckRock is a nonprofit journalism organization that gathered CDC data based on death certificates (MuckRock/Maternal-Mortality: A Repository of CDC National Center for Health Statistics Maternal Mortality Data and a Selection of State Data, from Michigan, Minnesota and North Carolina, about Maternal Deaths, n.d.). By using this dataset, I was able to map different mortality rates from both before and after the pandemic. These mortality rates represent the number of pregnancy-related deaths divided by the total number of maternal deaths in each state. These maps provided me with a base for researching different COVID-19 policies per state and their maternal health policies. 

The risk of maternal mortality increases when societal influences play a role in health care, preexisting conditions complicate pregnancy, and new pregnancy-related (maternal) morbidities further hinder a pregnant person from a healthy gestation. In the next post, I will examine how comorbidities of health impact maternal mortality, both before and during the pandemic. 




